theme: minima
title: Kitet Student
author: kitetstudent
email: tulipke.help@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  learning programming. 

# social links
twitter_username: tulipke # DO NOT include the @ character, or else the build will fail!
github_username:  kitetstudent # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
